apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_YOUR_REPO_URL   # e.g. https://github.com/<you>/fraud-gitops-lab.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: fraud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
